const PAGE=document.body.dataset.page;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const CO={'TechNova Labs':['Technology','Bengaluru','Product engineering team building SaaS tools for campuses.'],'DataBridge Analytics':['Analytics','Hyderabad','Turns raw data into decisions for retail and logistics clients.'],'PixelCraft Studio':['Design','Chennai','Product design studio for mobile-first startups.'],'GrowthSpark':['Marketing','Mumbai','Growth marketing agency for consumer brands.'],'CloudNest':['Technology','Pune','Cloud platform engineering and developer tooling.'],'FinEdge':['Finance','Mumbai','Fintech analytics and lending products.'],
'StoryLoop Media':['Media','Mumbai','Digital media house creating content for education and consumer brands.'],'SecureGrid':['Cybersecurity','Hyderabad','Managed security services and threat monitoring for enterprises.'],'BuildWell Infra':['Engineering','Coimbatore','Civil and infrastructure contractor delivering commercial and residential projects.'],'CarePlus Hospitals':['Healthcare','Chennai','Multi-speciality hospital network focused on patient experience and operations.'],'PeopleFirst Consulting':['HR','Bengaluru','Recruitment and HR advisory for startups and mid-size firms.'],'VoltEdge Systems':['Electronics','Coimbatore','Embedded hardware and IoT products for industrial automation.'],'LearnLoop':['Education','Bengaluru','EdTech platform delivering live classes and learning content.'],'Lexora Associates':['Legal','Delhi','Corporate and IP law firm with a structured internship programme.'],'SwiftMove Logistics':['Logistics','Chennai','Supply chain and last-mile delivery operations across South India.'],'TexWeave Apparel':['Textile & Apparel','Tiruppur','Knitwear manufacturer and exporter supplying global fashion brands.']},CN=Object.keys(CO);
const mk=(id,t,c,loc,mode,type,lvl,dur,pay,paid,sk,dl)=>({id,t,c,loc,mode,type,lvl,dur,pay,paid,sk,dl,ind:CO[c][0],exp:lvl=='Entry'?'0–1 yrs':'1–2 yrs',posted:(1+id.length*2%5+id.charCodeAt(1)%4)+' days ago'});
const O=[mk('i1','Software Development Intern','TechNova Labs','Bengaluru','Hybrid','Internship','Entry','3 months','₹20,000/mo',1,['Python','React','Node.js'],'30 Nov 2026'),mk('i2','Data Analyst Intern','DataBridge Analytics','Hyderabad','Remote','Internship','Entry','6 months','₹15,000/mo',1,['SQL','Data Analytics','Python'],'15 Nov 2026'),mk('i3','UI/UX Design Intern','PixelCraft Studio','Chennai','Hybrid','Internship','Entry','3 months','₹12,000/mo',1,['Figma','UI/UX'],'20 Nov 2026'),mk('i4','Marketing Intern','GrowthSpark','Mumbai','Remote','Internship','Entry','2 months','Unpaid',0,['SEO','Analytics','Content'],'10 Nov 2026'),
mk('j1','Software Developer','CloudNest','Pune','Hybrid','Job','Entry','Full-time','₹6–9 LPA',1,['Java','SQL','Node.js'],'05 Dec 2026'),mk('j2','Data Analyst','DataBridge Analytics','Bengaluru','On-site','Job','Junior','Full-time','₹5–8 LPA',1,['SQL','Machine Learning','AI'],'01 Dec 2026'),mk('j3','UI/UX Designer','PixelCraft Studio','Chennai','Remote','Job','Junior','Full-time','₹5–7 LPA',1,['Figma','UI/UX'],'28 Nov 2026'),mk('j4','Web Developer','TechNova Labs','Bengaluru','Hybrid','Job','Entry','Full-time','₹5–8 LPA',1,['JavaScript','React','Node.js'],'12 Dec 2026'),mk('j5','Business Analyst','FinEdge','Mumbai','On-site','Job','Junior','Full-time','₹6–10 LPA',1,['SQL','Data Analytics'],'18 Dec 2026'),
mk('i5','Content Writing Intern','StoryLoop Media','Mumbai','Remote','Internship','Entry','2 months','₹8,000/mo',1,['Content Writing','SEO'],'25 Nov 2026'),mk('i6','Cybersecurity Intern','SecureGrid','Hyderabad','Hybrid','Internship','Entry','3 months','₹15,000/mo',1,['Cybersecurity','Python'],'30 Nov 2026'),mk('i7','Finance & Accounting Intern','FinEdge','Mumbai','On-site','Internship','Entry','3 months','₹10,000/mo',1,['Excel','Data Analytics'],'22 Nov 2026'),mk('i8','Civil Engineering Intern','BuildWell Infra','Coimbatore','On-site','Internship','Entry','2 months','₹8,000/mo',1,['AutoCAD','Communication'],'18 Nov 2026'),mk('i9','Hospital Operations Intern','CarePlus Hospitals','Chennai','On-site','Internship','Entry','2 months','Unpaid',0,['Communication','Excel'],'12 Nov 2026'),mk('i10','HR & Recruitment Intern','PeopleFirst Consulting','Bengaluru','Hybrid','Internship','Entry','3 months','₹10,000/mo',1,['Recruitment','Communication'],'28 Nov 2026'),mk('i11','Embedded Systems Intern','VoltEdge Systems','Coimbatore','On-site','Internship','Entry','6 months','₹12,000/mo',1,['Embedded C','Python'],'05 Dec 2026'),mk('i12','Teaching & Content Intern','LearnLoop','Bengaluru','Remote','Internship','Entry','3 months','₹9,000/mo',1,['Communication','Content Writing'],'20 Nov 2026'),mk('i13','Legal Research Intern','Lexora Associates','Delhi','On-site','Internship','Entry','2 months','Unpaid',0,['Legal Research','Content Writing'],'15 Nov 2026'),mk('i14','Supply Chain Intern','SwiftMove Logistics','Chennai','Hybrid','Internship','Entry','6 months','₹12,000/mo',1,['Excel','Data Analytics'],'01 Dec 2026'),mk('i15','Apparel Merchandising Intern','TexWeave Apparel','Tiruppur','On-site','Internship','Entry','3 months','₹8,000/mo',1,['Merchandising','Communication'],'30 Nov 2026'),
mk('j6','Cybersecurity Analyst','SecureGrid','Hyderabad','Hybrid','Job','Junior','Full-time','₹6–10 LPA',1,['Cybersecurity','Python'],'20 Dec 2026'),mk('j7','Junior Accountant','FinEdge','Mumbai','On-site','Job','Entry','Full-time','₹3.5–5 LPA',1,['Excel','Tally'],'15 Dec 2026'),mk('j8','Site Engineer (Civil)','BuildWell Infra','Coimbatore','On-site','Job','Entry','Full-time','₹3.5–5 LPA',1,['AutoCAD','Communication'],'10 Dec 2026'),mk('j9','Hospital Operations Executive','CarePlus Hospitals','Chennai','On-site','Job','Entry','Full-time','₹3–4.5 LPA',1,['Communication','Excel'],'08 Dec 2026'),mk('j10','HR Executive – Recruitment','PeopleFirst Consulting','Bengaluru','Hybrid','Job','Entry','Full-time','₹3.5–5 LPA',1,['Recruitment','Communication'],'14 Dec 2026'),mk('j11','Embedded Systems Engineer','VoltEdge Systems','Coimbatore','On-site','Job','Junior','Full-time','₹4–7 LPA',1,['Embedded C','Python'],'22 Dec 2026'),mk('j12','Content Strategist','StoryLoop Media','Mumbai','Remote','Job','Junior','Full-time','₹4–6 LPA',1,['Content Writing','SEO'],'18 Dec 2026'),mk('j13','Sales Development Representative','GrowthSpark','Mumbai','Hybrid','Job','Entry','Full-time','₹3.5–6 LPA',1,['Communication','SEO'],'12 Dec 2026'),mk('j14','Supply Chain Executive','SwiftMove Logistics','Chennai','On-site','Job','Junior','Full-time','₹4–6 LPA',1,['Excel','Data Analytics'],'16 Dec 2026'),mk('j15','Junior Legal Associate','Lexora Associates','Delhi','On-site','Job','Junior','Full-time','₹4–7 LPA',1,['Legal Research','Communication'],'20 Dec 2026'),mk('j16','Teaching Associate','LearnLoop','Bengaluru','Remote','Job','Entry','Full-time','₹3–5 LPA',1,['Communication','Content Writing'],'11 Dec 2026'),mk('j17','Apparel Merchandiser','TexWeave Apparel','Tiruppur','On-site','Job','Entry','Full-time','₹3–4.5 LPA',1,['Merchandising','Excel'],'09 Dec 2026')];
const get=id=>O.find(o=>o.id==id);
const IMP={i1:'dev',i2:'data',i3:'ux',i4:'mk',j1:'code',j2:'ml',j3:'ui',j4:'web',j5:'ba',i5:'wr',i6:'cy',i7:'fi',i8:'ci',i9:'hc',i10:'hr',i11:'el',i12:'ed',i13:'lw',i14:'lo',i15:'ta',j6:'cy2',j7:'ac',j8:'se',j9:'hc2',j10:'hr2',j11:'em',j12:'wr2',j13:'sa',j14:'lo2',j15:'lw2',j16:'ed2',j17:'ta2'};
const IA={dev:'Student coding on a laptop',data:'Student analysing data on a laptop',ux:'UI wireframe sketches on paper',mk:'Marketing performance chart'};
Object.assign(IA,{code:'Code editor with a program open',ml:'Neural network diagram',ui:'UI design components',web:'Website in a browser window',ba:'Business analytics dashboard'});
const REV=[['Aarav Menon','B.Tech CSE, VIT Vellore','TechNova Labs',5,'My internship gave me real React tickets from week one. My mentor reviewed every pull request.'],['Sneha Iyer','BCA, Christ University','DataBridge Analytics',5,'I built SQL dashboards on live data. The remote setup was smooth and the team was supportive.'],['Rahul Verma','B.Des, NID Ahmedabad','PixelCraft Studio',4,'Great exposure to user research and Figma critiques. Deadlines were tight but fair.'],['Priya Nair','BBA, Mount Carmel College','GrowthSpark',4,'I ran two campaigns on my own. It was unpaid, but the portfolio work helped me land a paid role.'],['Karthik S','B.E. ISE, RVCE','CloudNest',5,'The hiring process was clear and quick, and I always knew my application status.'],['Meera Joshi','MBA, SP Jain','FinEdge',4,'Good mentoring and a real analyst workload. The application tracker kept me organised.']];
(function(){try{const r=JSON.parse(localStorage.getItem('internova-rev')||'[]');r.reverse().forEach(x=>REV.unshift(x))}catch(e){}})();
const stars=n=>`<span style="color:#B45309;letter-spacing:2px" role="img" aria-label="${n} out of 5 stars">${'★'.repeat(n)}${'☆'.repeat(5-n)}</span>`;
const rc=r=>`<article class="card rv">${stars(r[3])}<p style="margin-top:8px">“${r[4]}”</p><div class="ct" style="margin-top:12px"><span class="lg">${r[0][0]}</span><div><b>${r[0]}</b><p class="mt" style="margin:0">${r[1]} · ${r[2]}</p></div></div></article>`;
const rv=c=>{const l=REV.filter(r=>r[2]==c);return l.length?'<h3>Student reviews</h3>'+l.map(r=>`<p>${stars(r[3])} “${r[4]}”<br><span class="mt">${r[0]}, ${r[1]}</span></p>`).join(''):''};
function wr(){openM(`<h2>Write a review</h2><form onsubmit="postRv(event)"><label>Your name<input name="n" required value="${P.name}"></label><label>College and course<input name="k" required></label><label>Company<select name="c">${CN.map(n=>`<option>${n}</option>`).join('')}</select></label><label>Rating<select name="r"><option value="5">5 – Excellent</option><option value="4">4 – Good</option><option value="3">3 – Okay</option><option value="2">2 – Poor</option><option value="1">1 – Very poor</option></select></label><label>Your review<textarea name="t" rows="3" required></textarea></label><button class="btn">Post review</button></form>`)}
function postRv(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.target));const nr=[f.n,f.k,f.c,+f.r,f.t];try{const r=JSON.parse(localStorage.getItem('internova-rev')||'[]');r.unshift(nr);localStorage.setItem('internova-rev',JSON.stringify(r))}catch(x){}REV.unshift(nr);closeM();if(PAGE=='home'){render();toast('Thanks! Your review is posted');setTimeout(()=>$('#rev').scrollIntoView(),80)}else toast('Thanks! Your review is posted')}
Object.assign(IA,{wr:'Writer working on a notebook',wr2:'Content creator at a laptop',cy:'Cybersecurity code on a screen',cy2:'Security analyst working on a laptop',fi:'Finance and accounting work',ac:'Accounting and money management',ci:'Civil engineer reviewing blueprints on site',se:'Engineers at a construction site',hc:'Healthcare professional with a stethoscope',hc2:'Hospital and medical team',hr:'Team meeting in an office',hr2:'Recruiter interviewing a candidate',el:'Electronic circuit board',em:'Engineer working on electronics',ed:'Students in a classroom',ed2:'Teacher helping students',lw:'Gavel and legal books',lw2:'Legal documents on a desk',lo:'Warehouse and logistics',lo2:'Delivery and supply chain',ta:'Garments and textile production',ta2:'Apparel on a rack',sa:'Sales team discussing a deal'});
const DPH={dev:'images/dev.jpg',data:'images/data.jpg',ux:'images/ux.jpg',mk:'images/mk.jpg',fi:'images/fi.jpg',hc:'images/hc.jpg',ci:'images/ci.jpg',el:'images/el.jpg',cy:'images/cy.jpg',hr:'images/hr.jpg',ed:'images/ed.jpg',lw:'images/lw.jpg',wr:'images/wr.jpg',lo:'images/lo.jpg',ta:'images/ta.jpg'};
const AL={"code": "dev", "web": "dev", "ml": "data", "ui": "ux", "ba": "fi", "ac": "fi", "cy2": "cy", "se": "ci", "hc2": "hc", "hr2": "hr", "em": "el", "wr2": "wr", "sa": "mk", "lo2": "lo", "lw2": "lw", "ed2": "ed", "ta2": "ta"};
const phu=k=>DPH[AL[k]||k]||'';
const fb=k=>DPH[AL[k]||k]||'data:image/gif;base64,R0lGODlhAQABAAAAACw=';
const img=(o,m)=>{const k=IMP[o.id];return `<div class="im ${m?'big':''}"><img src="${phu(k)||fb(k)}" alt="${IA[k]||o.ind}" loading="lazy" onerror="this.onerror=null;this.src=fb('${k}')"></div>`};
const DOMS=[['Technology','dev'],['Analytics','data'],['Design','ux'],['Marketing','mk'],['Finance','fi'],['Healthcare','hc'],['Engineering','ci'],['Electronics','el'],['Cybersecurity','cy'],['HR','hr'],['Education','ed'],['Legal','lw'],['Media','wr'],['Logistics','lo'],['Textile & Apparel','ta']];
const dtile=(d,i)=>{const n=O.filter(o=>o.ind==d[0]).length;return `<button class="dt" onclick="dom(${i})"><img src="${phu(d[1])}" alt="" loading="lazy" onerror="this.onerror=null;this.src=fb('${d[1]}')"><span>${d[0]}<small>${n} opening${n==1?'':'s'}</small></span></button>`};
function dom(i){$('#ind-home').value=DOMS[i][0];run('home');$('#search').scrollIntoView()}
const SK=['Python','Java','JavaScript','SQL','Machine Learning','AI','Data Analytics','UI/UX','Figma','React','Node.js','Excel','Cybersecurity','AutoCAD','Content Writing'];
const SEL={loc:['Location',['Bengaluru','Hyderabad','Chennai','Mumbai','Pune','Coimbatore','Tiruppur','Delhi'],o=>o.loc],mode:['Remote / Hybrid',['Remote','Hybrid','On-site'],o=>o.mode],type:['Opportunity Type',['Internship','Job'],o=>o.type],lvl:['Experience Level',['Entry','Junior'],o=>o.lvl],dur:['Duration',['2 months','3 months','6 months'],o=>o.dur],paid:['Paid / Unpaid',['Paid','Unpaid'],o=>o.paid?'Paid':'Unpaid'],sk:['Skills',SK.concat(['SEO','Tally','Embedded C','Recruitment','Merchandising','Legal Research','Communication']),o=>o.sk],ind:['Domain',DOMS.map(d=>d[0]),o=>o.ind]};
const KS={home:['ind','loc','type','lvl','mode'],Internship:['ind','sk','loc','dur','mode','paid'],Job:['ind','loc','lvl','sk','mode']};
const CH=[['Internship',o=>o.type=='Internship'],['Full-time',o=>o.type=='Job'],['Remote',o=>o.mode=='Remote'],['Hybrid',o=>o.mode=='Hybrid'],['Entry Level',o=>o.lvl=='Entry']];
const ch={home:new Set,Internship:new Set,Job:new Set};
let saved=new Set,A=[],U=0,cur=PAGE,tab=-1;
const P={name:'Ananya Rao',email:'ananya.rao@example.com',phone:'+91 98765 43210',headline:'Final-year Computer Science student',edu:'B.E. Computer Science, 2026',exp:'Web development intern, campus startup',certs:'Google Data Analytics Certificate',pref:'Remote / Hybrid · Bengaluru',skills:['Python','SQL','React'],projects:[{t:'Campus Event App',d:'React app for club events and RSVPs.'}],resume:null};

const KEY='internova-v1';
const du2url=d=>{try{const [h,b]=d.split(','),mt=h.match(/:(.*?);/)[1],bin=atob(b),u=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)u[i]=bin.charCodeAt(i);return URL.createObjectURL(new Blob([u],{type:mt}))}catch(e){return ''}};
function save(){try{localStorage.setItem(KEY,JSON.stringify({saved:[...saved],A,U,P:{...P,resume:P.resume?{name:P.resume.name,du:P.resume.du||''}:null}}))}catch(e){}}
(function(){try{const d=JSON.parse(localStorage.getItem(KEY)||'null');if(d){saved=new Set(d.saved||[]);A=d.A||[];U=d.U||0;Object.assign(P,d.P||{});if(P.resume)P.resume.url=P.resume.du?du2url(P.resume.du):''}}catch(e){}})();
const pct=()=>(P.name&&P.email&&P.phone?15:0)+(P.edu?15:0)+(P.skills.length?15:0)+(P.projects.length?15:0)+(P.certs?10:0)+(P.exp?10:0)+(P.resume?15:0)+(P.pref?5:0);
const ST=['Applied','Under Review','Shortlisted','Interview','Selected','Rejected'],SC=['#3B82F6','#F59E0B','#F97316','#1D4ED8','#10B981','#EF4444'],NX=['Wait for recruiter review','Recruiter is reviewing your profile','Prepare for your interview round','Attend your interview','Offer details will arrive by email','Keep exploring — more roles are waiting'];
const badge=s=>`<span class="bd" style="--c:${SC[s]}"><i></i>${ST[s]}</span>`;
function tlh(s){const r=s==5,p=r?1:s;return `<div class="tl" role="img" aria-label="Status: ${ST[s]}">${ST.slice(0,5).map((n,i)=>`<div class="st ${i<=p?'dn':''} ${r&&i==1?'rj':''}" style="--d:${i*.25}s"><span>${r&&i==1?'✕':(i<p||(i==p&&s==4))?'✓':i+1}</span><small>${n}</small></div>`).join('')}<u style="--w:${p*20}%"></u></div>${r?'<p class="rjt">✕ Rejected</p>':''}`}
function card(o){return `<article class="card op" tabindex="0" onclick="det('${o.id}')" onkeydown="if(event.key=='Enter')det('${o.id}')">${img(o)}<div class="ct"><span class="lg">${o.c[0]}</span><div><h3>${o.t}</h3><p class="mt" style="margin:0">${o.c}</p></div></div><p class="mt">${o.loc} · ${o.mode} · ${o.type=='Job'?o.exp:o.dur}</p><div class="tg">${o.sk.map(s=>`<span>${s}</span>`).join('')}</div><p class="mt">${o.pay} · ${o.type=='Job'?'Posted '+o.posted:'Apply by '+o.dl}</p><div class="ac"><button class="sv ${saved.has(o.id)?'on':''}" data-id="${o.id}" aria-pressed="${saved.has(o.id)}" onclick="sv(event,'${o.id}')">${saved.has(o.id)?'♥ Saved':'♡ Save'}</button><button class="btn s" onclick="ap(event,'${o.id}')">Apply →</button></div></article>`}
function sv(e,id){e&&e.stopPropagation();saved.has(id)?saved.delete(id):saved.add(id);const on=saved.has(id);$$(`.sv[data-id="${id}"]`).forEach(b=>{b.classList.toggle('on',on);b.setAttribute('aria-pressed',on);b.textContent=on?'♥ Saved':'♡ Save'});save();toast(on?'Saved to your profile':'Removed from saved');if(cur=='profile')rr()}
function bar(k){return `<div class="card fb"><label class="sr" for="q-${k}">Search</label><input id="q-${k}" type="search" placeholder="Search jobs, internships, skills..." oninput="run('${k}')"><div class="sel">${KS[k].map(f=>`<label>${SEL[f][0]}<select id="${f}-${k}" onchange="run('${k}')"><option value="">All</option>${SEL[f][1].map(v=>`<option>${v}</option>`).join('')}</select></label>`).join('')}</div><div class="chips" role="group" aria-label="Quick filters">${CH.map((c,i)=>`<button type="button" class="chip" aria-pressed="false" onclick="chip(this,'${k}',${i})">${c[0]}</button>`).join('')}<button type="button" class="chip" onclick="clr('${k}')">Clear Filters</button></div></div><p id="cnt-${k}" class="mt" role="status"></p><div id="res-${k}" class="grid"></div>`}
function run(k){const q=$('#q-'+k).value.toLowerCase().trim(),vs=KS[k].map(f=>$(`#${f}-${k}`).value),act=q||vs.some(x=>x)||ch[k].size;let r=O.filter(o=>(k=='home'||o.type==k)&&(!q||[o.t,o.c,o.loc,o.type,o.ind,...o.sk].join(' ').toLowerCase().includes(q))&&KS[k].every((f,i)=>{const x=SEL[f][2](o);return !vs[i]||(Array.isArray(x)?x.includes(vs[i]):x==vs[i])})&&[...ch[k]].every(i=>CH[i][1](o)));
$('#res-'+k).innerHTML=(k=='home'&&!act)?'':r.map(card).join('')||'<div class="card">No matches yet. Try removing a filter or searching a different skill.</div>';$('#cnt-'+k).textContent=(k=='home'&&!act)?'':r.length+' opportunit'+(r.length==1?'y':'ies')+' found'}
function chip(b,k,i){ch[k].has(i)?ch[k].delete(i):ch[k].add(i);b.classList.toggle('on');b.setAttribute('aria-pressed',ch[k].has(i));run(k)}
function clr(k){$('#q-'+k).value='';KS[k].forEach(f=>$(`#${f}-${k}`).value='');ch[k].clear();$$('#app .chip.on').forEach(b=>{if(b.getAttribute('aria-pressed'))b.classList.remove('on')});$$('#app .chip[aria-pressed]').forEach(b=>b.setAttribute('aria-pressed',false));run(k)}
function skl(s){$('#q-home').value=s;run('home');$$('.skc').forEach(b=>b.classList.toggle('on',b.textContent==s));$('#search').scrollIntoView()}
const HW=[['Discover','Discover opportunities that match your skills.'],['Learn','Learn relevant skills with focused courses.'],['Apply','Apply confidently with your saved profile.'],['Grow','Grow your career from first internship to full-time role.']];
const sec=(h,b)=>`<section class="wrap rv"><h2>${h}</h2>${b}</section>`;
const V={home:()=>`<div class="hero wrap"><div class="rv in"><span class="kick">FROM CAMPUS TO CAREER</span><h1>Your First Internship Can Start Your Journey.</h1><p class="lead"><b>Your Skills. Your Opportunity.</b><br>Discover internships and entry-level jobs that match your skills, interests, and career goals.</p><div class="row"><button class="btn" onclick="show('Job')">Explore Opportunities →</button><button class="btn b" onclick="show('Internship')">Find Internships →</button></div></div><div class="hv"><img src="images/hero.jpg" alt="Student studying with a notebook and headphones by a window" fetchpriority="high"></div></div>
<section id="search" class="wrap rv"><h2>Find what fits you</h2>${bar('home')}</section>
${sec('Explore by domain',`<p class="mt">Pick your field and see internships and jobs in it.</p><div class="dg">${DOMS.map(dtile).join('')}</div>`)}
${sec('Featured Internships',`<div class="grid">${O.filter(o=>o.type=='Internship').slice(0,3).map(card).join('')}</div>`)}${sec('Featured Jobs',`<div class="grid">${O.filter(o=>o.type=='Job').slice(0,3).map(card).join('')}</div>`)}
${sec('Popular Skills',`<div class="chips">${SK.map(s=>`<button class="chip skc" onclick="skl('${s}')">${s}</button>`).join('')}</div>`)}
<section class="wrap"><h2>How Internova Works</h2><div class="hw">${HW.map((h,i)=>`<div class="card rv" style="transition-delay:${i*.3}s"><b>${i+1}</b><h3>${h[0]}</h3><p class="mt">${h[1]}</p></div>`).join('')}</div></section>
<section class="wrap rv"><div class="g2"><div class="card"><h2>Your profile, ready to apply</h2><div class="av">${P.name[0]}</div><b>${P.name}</b><p class="mt">${P.headline}</p><div class="pb"><i style="width:${pct()}%"></i></div><p class="mt">${pct()}% complete</p><button class="btn s" onclick="show('profile')">Build your profile</button></div><div class="card"><h2>Resume</h2><p class="mt">Upload once. Your resume is attached automatically when you apply.</p><div class="row" style="margin-top:14px"><button class="btn" onclick="$('#rf').click()">Upload Resume</button><button class="btn o" onclick="show('profile')">Manage resume</button></div></div></div></section>
${sec('Companies hiring students',`<div class="grid">${CN.map((n,i)=>`<button class="card op" style="text-align:left;font:inherit" onclick="cmp(${i})"><span class="lg">${n[0]}</span><h3 style="margin-top:8px">${n}</h3><p class="mt">${CO[n][0]} · ${CO[n][1]}</p></button>`).join('')}</div>`)}
<span id="rev"></span>${sec('What students say',`<div class="grid">${REV.map(rc).join('')}</div><p style="margin-top:14px"><button class="btn s o" onclick="wr()">Write a review</button></p>`)}${sec('Track every application',`<div class="card"><h3>Software Development Intern · TechNova Labs</h3>${tlh(2)}<button class="btn s b" onclick="show('applications')">Open My Applications</button></div>`)}
<section class="wrap rv"><div class="cta"><h2>Discover Opportunities. Start Your Journey.</h2><p>Create your free profile and apply in minutes.</p><button class="btn" onclick="show('signup')">Get Started →</button></div></section>`,
Internship:()=>`<section class="wrap"><h1>Find Your Next Internship</h1><p class="lead">Short, skill-building roles for students.</p>${bar('Internship')}</section>`,
Job:()=>`<section class="wrap"><h1>Find Your Next Opportunity</h1><p class="lead">Entry-level jobs for fresh graduates.</p>${bar('Job')}</section>`,
applications:()=>`<section class="wrap"><h1>My Applications</h1><div id="tabs" class="chips" role="tablist" style="margin:16px 0"></div><div id="al" class="stack"></div></section>`,
profile:()=>`<section class="wrap"><span class="kick">STUDENT PROFILE</span><h1>Build a Profile That Gets Noticed.</h1><div class="pg"><div class="card"><div class="av">${P.name[0]}</div><h2>${P.name}</h2><p>${P.headline}</p><p class="mt">${P.email}<br>${P.phone}</p><div class="pb"><i id="pbi" style="width:0"></i></div><b>${pct()}% Profile Complete</b><div class="row" style="margin-top:14px"><button class="btn s" onclick="editP()">Edit Profile</button></div></div><div class="stack">
<div class="card"><h3>Education</h3><p>${P.edu||'Add your education'}</p></div>
<div class="card"><h3>Skills</h3><div class="tg">${P.skills.map(s=>`<span>${s}</span>`).join('')}</div><form class="row" onsubmit="addSk(event)"><label class="sr" for="ns">New skill</label><input id="ns" placeholder="Add a skill" style="max-width:240px"><button class="btn s">Add Skill</button></form></div>
<div class="card"><h3>Projects</h3>${P.projects.map(p=>`<p><b>${p.t}</b><br><span class="mt">${p.d}</span></p>`).join('')}<button class="btn s o" style="margin-top:10px" onclick="addPr()">Add Project</button></div>
<div class="card"><h3>Certifications &amp; Experience</h3><p>${P.certs||'—'}</p><p>${P.exp||'—'}</p></div><div class="card"><h3>Career Preferences</h3><p>${P.pref||'—'}</p></div>
<div class="card"><h3>Resume</h3><p class="mt">${P.resume?'✓ '+P.resume.name:'No resume uploaded yet. It will be attached when you apply.'}</p><div class="row" style="margin-top:10px">${P.resume&&P.resume.url?`<a class="btn s o" href="${P.resume.url}" target="_blank" rel="noopener">View Resume</a><button class="btn s" onclick="$('#rf').click()">Replace Resume</button><a class="btn s o" href="${P.resume.url}" download="${P.resume.name}">Download Resume</a>`:`<button class="btn s" onclick="$('#rf').click()">Upload Resume</button>`}</div></div>
<div class="card"><h3>Saved Opportunities</h3><div class="stack" style="margin-top:10px">${[...saved].map(id=>get(id)).map(o=>`<div class="ac" style="margin:0"><button class="ib" onclick="det('${o.id}')">${o.t} · ${o.c}</button><button class="sv on" data-id="${o.id}" onclick="sv(event,'${o.id}')">♥ Saved</button></div>`).join('')||'<p class="mt">Nothing saved yet. Tap ♡ Save on any opportunity.</p>'}</div></div></div></div></section>`,
login:()=>`<div class="card auth"><h1 style="font-size:1.8rem">Welcome back</h1><form onsubmit="return au(event,0)"><label>Email<input type="email" required></label><label>Password<input type="password" required minlength="6"></label><label style="display:flex;gap:8px;align-items:center"><input type="checkbox" style="width:auto;min-height:0"> Remember me</label><button class="btn b">Sign In</button><button type="button" class="ib" onclick="show('forgot')">Forgot Password?</button></form><p class="mt">New here? <a href="#" onclick="show('signup');return false">Create an account</a></p></div>`,
signup:()=>`<div class="card auth"><h1 style="font-size:1.8rem">Create your account</h1><form onsubmit="return au(event,1)"><label>Full Name<input name="n" required></label><label>Email<input name="e" type="email" required></label><label>Password<input name="p" type="password" required minlength="6"></label><label>Confirm Password<input name="c" type="password" required></label><fieldset style="border:0"><legend>Account type</legend><label style="display:flex;gap:8px;align-items:center"><input type="radio" name="t" value="s" checked style="width:auto;min-height:0"> Student</label><label style="display:flex;gap:8px;align-items:center"><input type="radio" name="t" value="r" style="width:auto;min-height:0"> Employer / Recruiter</label></fieldset><button class="btn">Create Account</button></form></div>`,
forgot:()=>`<div class="card auth"><h1 style="font-size:1.8rem">Reset password</h1><form onsubmit="event.preventDefault();show('login','Reset link sent. Check your inbox.')"><label>Email<input type="email" required></label><button class="btn b">Send reset link</button></form></div>`};
function au(e,s){e.preventDefault();const f=Object.fromEntries(new FormData(e.target));if(s){if(f.p!=f.c)return toast('Passwords do not match'),false;P.name=f.n;P.email=f.e;U=1;save();if(f.t=='s')go('profile','Account created. Complete your profile.','edit');else go('home','Employer account created. Recruiter tools are not in this prototype.')}else{U=1;save();go('home','Welcome back, '+P.name.split(' ')[0])}return false}
const PG={home:'index.html',Internship:'internships.html',Job:'jobs.html',profile:'profile.html',applications:'applications.html',login:'login.html',signup:'signup.html',forgot:'forgot.html'};
function go(v,msg,flag){try{msg&&sessionStorage.setItem('flash',msg);flag&&sessionStorage.setItem('flag',flag)}catch(e){}location.href=PG[v]}
const show=go;
function signOut(){U=0;save();go('home','You have signed out')}
function navR(){$('#au').innerHTML=U?'<button class="ib" onclick="signOut()">Sign out</button>':'<button class="ib" onclick="show(\'login\')">Login</button><button class="btn s" onclick="show(\'signup\')">Get Started</button>'}
function render(){cur=PAGE;$('#app').innerHTML=V[PAGE]();$$('#nv a').forEach(a=>a.classList.toggle('on',a.dataset.v==PAGE));$('#nv').classList.remove('open');if(KS[PAGE])run(PAGE);if(PAGE=='applications')tr();if(PAGE=='profile')anim();obs()}
const rr=()=>{const y=scrollY;$('#app').innerHTML=V.profile();anim();scrollTo(0,y)},anim=()=>setTimeout(()=>{const b=$('#pbi');b&&(b.style.width=pct()+'%')},80);
function obs(){const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&(e.target.classList.add('in'),io.unobserve(e.target))),{threshold:.12});$$('.rv:not(.in)').forEach(x=>io.observe(x))}
const sn=()=>{if(PAGE!='home')return location.href='index.html#search';$('#search').scrollIntoView();$('#q-home').focus()};
function tr(){$('#tabs').innerHTML=['All',...ST].map((n,i)=>`<button role="tab" aria-selected="${tab==i-1}" class="chip ${tab==i-1?'on':''}" onclick="tab=${i-1};tr()">${n} (${i?A.filter(a=>a.st==i-1).length:A.length})</button>`).join('');const L=A.filter(a=>tab<0||a.st==tab);$('#al').innerHTML=L.map(a=>{const o=get(a.oid);return `<article class="card op" tabindex="0" onclick="ad('${a.id}')" onkeydown="if(event.key=='Enter')ad('${a.id}')"><div class="ac" style="margin:0"><div><h3>${o.t}</h3><p class="mt" style="margin:0">${o.c} · Applied ${a.date}</p></div>${badge(a.st)}</div><p class="mt"><b>Next step:</b> ${NX[a.st]}</p>${tlh(a.st)}</article>`}).join('')||`<div class="card"><h3>${A.length?'Nothing in this stage yet':'No applications yet'}</h3><p class="mt">Find a role that fits and apply in minutes.</p><div class="row" style="margin-top:12px"><button class="btn s" onclick="show('Internship')">Browse internships</button><button class="btn s o" onclick="show('Job')">Browse jobs</button></div></div>`}
function ad(id){const a=A.find(x=>x.id==id),o=get(a.oid);openM(`<h2>${o.t}</h2><p>${o.c} · ${o.loc}</p><p class="mt">Application ID <b>${a.id}</b> · Applied ${a.date}</p><div>${badge(a.st)}</div>${tlh(a.st)}<p><b>Next step:</b> ${NX[a.st]}</p><label>Update status (demo)<select onchange="us('${a.id}',this.value)">${ST.map((s,i)=>`<option value="${i}" ${i==a.st?'selected':''}>${s}</option>`).join('')}</select></label>`)}
function us(id,v){A.find(x=>x.id==id).st=+v;save();ad(id);if(cur=='applications')tr()}
function det(id){const o=get(id),i=o.type=='Job';openM(`${img(o,1)}<h2>${o.t}</h2><p><a href="#" onclick="cmp(${CN.indexOf(o.c)});return false">${o.c}</a> · ${o.loc} · ${o.mode}</p><p class="mt">${i?o.exp+' · '+o.pay:o.dur+' · '+o.pay} · Deadline ${o.dl}</p><div class="tg">${o.sk.map(s=>`<span>${s}</span>`).join('')}</div><h3>Description</h3><p>Join ${o.c} as a ${o.t} and work on real projects with experienced mentors. You will learn by doing and build work that strengthens your ${i?'career':'first step into industry'}.</p><h3>Responsibilities</h3><ul><li>Support the team on day-to-day deliverables</li><li>Apply ${o.sk[0]} and ${o.sk[1]||o.sk[0]} on live projects</li><li>Share progress in weekly reviews</li></ul><h3>Requirements</h3><ul><li>Pursuing or holding a relevant degree</li><li>Working knowledge of ${o.sk.join(', ')}</li><li>Clear communication and curiosity</li></ul><h3>Benefits</h3><ul><li>Mentorship and learning budget</li><li>${i?'Health cover and paid leave':'Certificate and pre-placement offer chance'}</li><li>Flexible ${o.mode.toLowerCase()} setup</li></ul>${rv(o.c)}<div class="row"><button class="btn" onclick="ap(null,'${o.id}')">Apply Now →</button><button class="sv ${saved.has(id)?'on':''}" data-id="${id}" onclick="sv(event,'${id}')">${saved.has(id)?'♥ Saved':'♡ Save'}</button></div>`)}
function cmp(i){const n=CN[i];openM(`<h2>${n}</h2><p class="mt">${CO[n][0]} · ${CO[n][1]}</p><p>${CO[n][2]}</p><h3>Open roles</h3>${O.filter(o=>o.c==n).map(o=>`<button class="btn s o" onclick="det('${o.id}')">${o.t}</button>`).join('')}`)}
function ap(e,id){e&&e.stopPropagation();const o=get(id);if(A.some(a=>a.oid==id))return show('applications','You already applied to this role');openM(`<h2>Apply to ${o.t}</h2><p class="mt">${o.c} · ${o.loc}</p><form onsubmit="sub(event,'${id}')"><label>Full Name<input name="n" required value="${P.name}"></label><label>Email<input name="e" type="email" required value="${P.email}"></label><label>Phone<input name="p" type="tel" required value="${P.phone}"></label><label>Resume ${P.resume?`<span class="mt">✓ Using ${P.resume.name} from your profile</span>`:''}<input type="file" name="f" accept=".pdf,.doc,.docx" ${P.resume?'':'required'}></label><label>Skills<input name="s" value="${P.skills.join(', ')}"></label><label>Cover Letter<textarea name="c" rows="3" placeholder="Why are you a good fit?"></textarea></label><label>Availability<select name="a"><option>Immediately</option><option>Within 2 weeks</option><option>Within a month</option></select></label><div class="row"><button type="button" class="btn o" onclick="closeM()">Cancel</button><button class="btn">Submit Application</button></div></form>`)}
function sub(e,id){e.preventDefault();const o=get(id),f=e.target.f.files[0],a={id:'INV-'+(1000+Math.floor(Math.random()*9000)),oid:id,date:new Date().toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'}),st:0};if(f&&!P.resume)a.res=f.name;A.unshift(a);save();openM(`<div class="okc">✓</div><h2>Application Submitted Successfully!</h2><dl><dt>Application ID</dt><dd>${a.id}</dd><dt>Role</dt><dd>${o.t}</dd><dt>Company</dt><dd>${o.c}</dd><dt>Applied Date</dt><dd>${a.date}</dd><dt>Status</dt><dd>${badge(0)}</dd></dl><div class="row"><button class="btn" onclick="ad('${a.id}')">View Application</button><button class="btn b" onclick="closeM();show('applications')">Go to Applications</button></div>`)}
function editP(){openM(`<h2>Edit Profile</h2><form onsubmit="svP(event)">${[['name','Full Name'],['email','Email'],['phone','Phone'],['headline','Headline'],['edu','Education'],['exp','Experience'],['certs','Certifications'],['pref','Career Preferences']].map(f=>`<label>${f[1]}<input name="${f[0]}" value="${P[f[0]]||''}"></label>`).join('')}<div class="row"><button type="button" class="btn o" onclick="closeM()">Cancel</button><button class="btn">Save changes</button></div></form>`)}
function svP(e){e.preventDefault();Object.assign(P,Object.fromEntries(new FormData(e.target)));save();closeM();toast('Profile updated');cur=='profile'?rr():show('profile')}
function addSk(e){e.preventDefault();const v=$('#ns').value.trim();if(v&&!P.skills.includes(v)){P.skills.push(v);save();toast('Skill added')}rr()}
function addPr(){openM(`<h2>Add Project</h2><form onsubmit="event.preventDefault();P.projects.push({t:this.t.value,d:this.d.value});save();closeM();toast('Project added');rr()"><label>Project title<input name="t" required></label><label>Description<textarea name="d" rows="3" required></textarea></label><button class="btn">Add Project</button></form>`)}
function up(i){const f=i.files[0];if(!f)return;const url=URL.createObjectURL(f),rd=new FileReader();P.resume={name:f.name,url,du:''};rd.onload=()=>{if(f.size<1500000){P.resume.du=rd.result}save();toast('Resume uploaded');if(cur=='profile')rr()};rd.readAsDataURL(f);i.value=''}
function openM(h){$('#mb').innerHTML=h;$('#mod').classList.add('on');setTimeout(()=>{const f=$('#mb input,#mb button');f&&f.focus()},50)}
const closeM=()=>$('#mod').classList.remove('on');let tt;function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('on');clearTimeout(tt);tt=setTimeout(()=>t.classList.remove('on'),2800)}
addEventListener('keydown',e=>e.key=='Escape'&&closeM());$('#mod').addEventListener('click',e=>e.target.id=='mod'&&closeM());
navR();render();
try{const fl=sessionStorage.getItem('flash'),fg=sessionStorage.getItem('flag');sessionStorage.removeItem('flash');sessionStorage.removeItem('flag');if(fl)setTimeout(()=>toast(fl),200);if(fg=='edit'&&PAGE=='profile')setTimeout(editP,300)}catch(e){}
if(PAGE=='home'&&location.hash=='#search')setTimeout(()=>{$('#search').scrollIntoView();$('#q-home').focus()},150);
